language: python
python:
  - 2.7
  - 3.4
install:
  #- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  #- pip install -r requirements.txt
  #- pip install 
  # Install conda
  #- sudo -H pip install conda
  - sudo -H pip install auxlib
  - sudo -H pip install conda
  # install deps
  #- sudo -H conda init
  - sudo -H conda init
  #- sudo -H conda update conda --yes
  - sudo -H conda update conda --yes
  - deps='pip numpy pandas sklearn'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  - python setup.py install
script:
  - coverage run --source=inferelator_strawman setup.py test
after_success:
  - coveralls
