language: python
python:
  - 2.7
  - 3.4
install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=inferelator_strawman setup.py test
after_success:
  - coveralls
